### ISSUE TITLE
Question about Probability map

### ISSUE THREAD

**Issue by limyunn** [ahmedeqbal/PDF-UNet#1]
Awesome work! I have a question about the generation of probability maps in the article, I'm curious how to ensure the quality of the pseudo-mask of the generated synthetic images, if the mask quality of the synthetic images generated by the PMG network is not good, then it should have an impact on the subsequent segmentation of the PDF network as well, how to solve this problem?

**Comment by ahmedeqbal** [comment]
Thank you for your interest in our proposed research work. Your question is valid and reasonable. We generate probability maps from the synthetic images, but some of them are ambiguous or erroneous for our PDF-UNet model to train. We have manually removed those images, but we plan to develop an automated scheme to detect and discard such images in the future.

**Comment by limyunn** [comment]
Thanks for your reply!  Did you try to do a test time augmentaion while generating the probability map?  I'm curious if this way can filter out the noise from the probability map to some extent?

**Comment by limyunn** [comment]
Thanks for your reply! Did you try to do test time augmentaion while generating the probability map? I'm curious if this way can filter out the noise from the probability map to some extent?

**Comment by ahmedeqbal** [comment]
Dear, Yes, "Test Time Augmentation",
